name: "Restart Docker Container"

on:
  workflow_dispatch:
jobs:
  deploy-hetzner:
    name: Deployment hetzner
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to hetzner
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HETZNER_IP}}
          username: ${{secrets.HETZNER_USERNAME}}
          password: ${{secrets.HETZNER_PASSWORD}}
          script: |
            docker pull ${{ secrets.DOCKERHUB_TAG }}
            docker stop tuneflux || true
            docker rm tuneflux || true
            docker run -d --name tuneflux --network=tuneflux -e MONGO_DB_URI=${{secrets.MONGO_DB_URI}} -e GITHUB_CLIENT_ID=${{secrets.GHUB_CLIENT_ID}} -e GITHUB_CLIENT_SECRET=${{secrets.GHUB_CLIENT_SECRET}} -e BACKEND_URL=${{secrets.BACKEND_URL}} -p 8080:8080 ${{ secrets.DOCKERHUB_TAG }}